# Generated by Django 5.2.3 on 2025-06-15 21:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', tinymce.models.HTMLField(default='&copy; 2025 Twoja Nazwa. Wszelkie prawa zastrzeżone.', help_text='Tekst praw autorskich (np. © 2025 Nazwa Ośrodka. Wszelkie prawa zastrzeżone.). Możesz używać formatowania HTML.', verbose_name='Tekst Praw Autorskich')),
                ('address', tinymce.models.HTMLField(blank=True, help_text='Pełny adres ośrodka. Możesz używać formatowania HTML (np. łamanie linii za pomocą &lt;br&gt;).', null=True, verbose_name='Adres Ośrodka')),
                ('contact_email', models.EmailField(blank=True, help_text='Główny adres e-mail do kontaktu.', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Numer telefonu do kontaktu.', max_length=50, null=True)),
                ('mapa_strony_html', tinymce.models.HTMLField(blank=True, default="<ul><li><a href='/'>Strona główna</a></li><li><a href='/program/'>Program</a></li><li><a href='/buddyzm/'>Buddyzm</a></li><li><a href='/kontakt/'>Kontakt i wsparcie</a></li></ul>", help_text="Wprowadź listę linków HTML (np. &lt;ul&gt;&lt;li&gt;&lt;a href='/url/'&gt;Tekst&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;).", null=True, verbose_name="Sekcja 'Mapa Strony'")),
                ('zobacz_tez_html', tinymce.models.HTMLField(blank=True, default="<ul><li><a href='https://www.buddyzm.pl/polska/'>Buddyzm w Polsce</a></li><li><a href='https://www.buddyzm.pl/swiat/'>Buddyzm na świecie</a></li><li><a href='https://magazyn.buddyzm.pl/'>Magazyn Diamentowa Droga</a></li></ul>", help_text='Wprowadź listę linków HTML do powiązanych zasobów.', null=True, verbose_name="Sekcja 'Zobacz też'")),
                ('osrodki_na_slasku_html', tinymce.models.HTMLField(blank=True, default="<ul><li><a href='https://www.bielsko.buddyzm.pl/'>Bielsko-Biała</a></li><li><a href='https://www.gliwice.buddyzm.pl/'>Gliwice</a></li><li><a href='https://www.rybnik.buddyzm.pl/'>Rybnik</a></li></ul>", help_text='Wprowadź listę linków HTML do innych ośrodków w regionie.', null=True, verbose_name="Sekcja 'Ośrodki na Śląsku'")),
                ('bank_name', tinymce.models.HTMLField(blank=True, help_text='Nazwa banku (np. PKO BP). Możesz używać podstawowego formatowania HTML.', max_length=100, null=True, verbose_name='Nazwa banku')),
                ('bank_account_number', models.CharField(blank=True, help_text='Numer IBAN (np. PL 96 1020 1866 0000 1902 0091 1735).', max_length=50, null=True, verbose_name='Numer konta bankowego')),
                ('bank_swift_bic', models.CharField(blank=True, help_text='Kod SWIFT/BIC (np. BPKOPLPW).', max_length=20, null=True, verbose_name='Kod SWIFT/BIC')),
                ('transfer_title_hint', models.CharField(blank=True, default='Darowizna na cele kultu religijnego', help_text='Sugerowany tytuł przelewu (np. Darowizna na cele kultu religijnego).', max_length=255, null=True, verbose_name='Wskazówka do tytułu przelewu')),
            ],
            options={
                'verbose_name': 'Zawartość Stopki',
                'verbose_name_plural': 'Zawartość Stopki',
            },
        ),
        migrations.CreateModel(
            name='HeaderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', tinymce.models.HTMLField(default='Moja Strona Django', help_text='Wprowadź nazwę strony lub ośrodka. Możesz używać podstawowego formatowania HTML (np. <strong>, <em>).', verbose_name='Nazwa Strony/Ośrodka')),
                ('tagline', tinymce.models.HTMLField(blank=True, help_text='Krótki slogan lub opis wyświetlany pod nazwą strony w nagłówku. Możesz używać podstawowego formatowania HTML.', null=True, verbose_name='Slogan/Podtytuł')),
            ],
            options={
                'verbose_name': 'Zawartość Nagłówka',
                'verbose_name_plural': 'Zawartość Nagłówka',
            },
        ),
    ]
