# Generated by Django 5.2.3 on 2025-06-15 23:01

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footercontent',
            options={'verbose_name': 'Zawartość stopki', 'verbose_name_plural': 'Zawartości stopki'},
        ),
        migrations.RemoveField(
            model_name='footercontent',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='footercontent',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='footercontent',
            name='bank_swift_bic',
        ),
        migrations.RemoveField(
            model_name='footercontent',
            name='mapa_strony_html',
        ),
        migrations.RemoveField(
            model_name='footercontent',
            name='osrodki_na_slasku_html',
        ),
        migrations.RemoveField(
            model_name='footercontent',
            name='transfer_title_hint',
        ),
        migrations.AddField(
            model_name='footercontent',
            name='bank_info_html',
            field=tinymce.models.HTMLField(blank=True, help_text='Wprowadź wszystkie dane bankowe w jednym bloku HTML (np. nazwa banku, numer konta, SWIFT/BIC, tytuł przelewu). Użyj TinyMCE do formatowania.', verbose_name='Informacje Bankowe (HTML)'),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='osrodki_w_poblizu_html',
            field=tinymce.models.HTMLField(blank=True, help_text="Wprowadź listę linków do ośrodków w pobliżu w formacie HTML (np. &lt;ul&gt;&lt;li&gt;&lt;a href='/url/'&gt;Tekst&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;).", verbose_name="Sekcja 'Ośrodki w pobliżu' (HTML)"),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='address',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now, verbose_name='Adres ośrodka'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adres E-mail'),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numer Telefonu'),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='copyright_text',
            field=tinymce.models.HTMLField(verbose_name='Tekst praw autorskich'),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='zobacz_tez_html',
            field=tinymce.models.HTMLField(blank=True, default=django.utils.timezone.now, help_text="Wprowadź listę linków w formacie HTML (np. &lt;ul&gt;&lt;li&gt;&lt;a href='/url/'&gt;Tekst&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;).", verbose_name="Sekcja 'Zobacz też' (HTML)"),
            preserve_default=False,
        ),
    ]
