# Generated by Django 5.2.3 on 2025-06-16 02:11

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_alter_footercontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercontent',
            name='logo',
            field=models.ImageField(blank=True, help_text='Obraz logo wyświetlany w nagłówku.', null=True, upload_to='site_config/logos/', verbose_name='Logo strony'),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='address',
            field=tinymce.models.HTMLField(blank=True, help_text='Pełny adres ośrodka, może zawierać formatowanie HTML.', verbose_name='Adres ośrodka'),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='bank_info_html',
            field=tinymce.models.HTMLField(blank=True, help_text='Wprowadź wszystkie dane bankowe w jednym bloku HTML (np. nazwa banku, numer konta, SWIFT/BIC, tytuł przelewu).', verbose_name='Informacje Bankowe (HTML)'),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Główny adres e-mail do kontaktu.', max_length=254, null=True, verbose_name='Adres E-mail'),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Numer telefonu kontaktowego.', max_length=50, null=True, verbose_name='Numer Telefonu'),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='copyright_text',
            field=tinymce.models.HTMLField(blank=True, help_text='Tekst informacji o prawach autorskich (np. © 2023 Twoja Nazwa).', verbose_name='Tekst praw autorskich'),
        ),
        migrations.AlterField(
            model_name='headercontent',
            name='site_name',
            field=models.CharField(blank=True, help_text='Główna nazwa strony wyświetlana w nagłówku.', max_length=200, verbose_name='Nazwa Strony/Ośrodka'),
        ),
        migrations.AlterField(
            model_name='headercontent',
            name='tagline',
            field=models.CharField(blank=True, default=django.utils.timezone.now, help_text='Krótki slogan lub opis wyświetlany pod nazwą strony.', max_length=255, verbose_name='Slogan/Podtytuł'),
            preserve_default=False,
        ),
    ]
