# Generated by Django 5.2.3 on 2025-06-16 02:54

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0003_headercontent_logo_alter_footercontent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercontent',
            name='header_background_image',
            field=models.ImageField(blank=True, help_text='Obraz używany jako tło dla sekcji nagłówka strony.', null=True, upload_to='site_config/header_bgs/', verbose_name='Obraz tła nagłówka'),
        ),
        migrations.AlterField(
            model_name='headercontent',
            name='site_name',
            field=tinymce.models.HTMLField(blank=True, help_text='Główna nazwa strony wyświetlana w nagłówku. Możesz używać formatowania HTML.', max_length=200, verbose_name='Nazwa Strony/Ośrodka'),
        ),
        migrations.AlterField(
            model_name='headercontent',
            name='tagline',
            field=tinymce.models.HTMLField(blank=True, help_text='Krótki slogan lub opis wyświetlany pod nazwą strony. Możesz używać formatowania HTML.', max_length=255, verbose_name='Slogan/Podtytuł'),
        ),
    ]
