# Generated by Django 5.2.3 on 2025-06-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0004_headercontent_header_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headercontent',
            name='tagline',
        ),
    ]
