# Generated by Django 5.2.3 on 2025-06-15 12:28

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Tytuł aktualności')),
                ('slug', models.SlugField(blank=True, help_text="Przyjazny adres URL, np. 'pierwsza-aktualnosc'. Zostaw puste, aby wygenerować automatycznie.", max_length=250, unique=True)),
                ('content', tinymce.models.HTMLField(verbose_name='Treść aktualności')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='news_thumbnails/', verbose_name='Obraz miniatury')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data publikacji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aktualność',
                'verbose_name_plural': 'Aktualności',
                'ordering': ['-published_date'],
            },
        ),
    ]
