# Generated by Django 5.2.3 on 2025-06-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Zaznacz, aby przypiąć artykuł na górze listy.', verbose_name='Przypięta?'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Zaznacz, jeśli artykuł ma być widoczny publicznie.', verbose_name='Opublikowana?'),
        ),
    ]
