# Generated by Django 5.2.3 on 2025-06-18 09:09

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_is_pinned_article_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pin_order',
            field=models.PositiveIntegerField(default=0, help_text='Niższa liczba = wyższa pozycja na liście. Używane tylko dla przypiętych artykułów.', verbose_name='Kolejność przypięcia'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Treść artykułu/posta'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Zaznacz, aby przypiąć artykuł na górze listy. Artykuły nieprzypięte będą sortowane według daty publikacji.', verbose_name='Przypięta?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Zaznacz, jeśli artykuł ma być widoczny publicznie.', verbose_name='Opublikowana? artykuły nieopublikowane nie będą widoczne na stronie.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text="Przyjazny adres URL, np. 'nowy-kurs-medytacyjny'. Zostaw puste, aby wygenerować automatycznie.", max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Tytuł artykułu/posta'),
        ),
    ]
