# Generated by Django 5.2.3 on 2025-06-18 20:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_pin_order_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posty'},
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail_alignment',
            field=models.CharField(choices=[('LEFT', 'Do lewej'), ('RIGHT', 'Do prawej'), ('CENTER', 'Na środku')], default='CENTER', help_text='Wybierz pozycję miniatury względem tekstu.', max_length=6, verbose_name='Wyrównanie miniatury'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail_custom_width',
            field=models.PositiveIntegerField(blank=True, help_text="Wpisz szerokość w pikselach, jeśli powyżej wybrano 'Niestandardowy'.", null=True, verbose_name='Niestandardowa szerokość (px)'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail_size',
            field=models.CharField(choices=[('S', 'Mała (do 200px)'), ('M', 'Średnia (do 350px)'), ('L', 'Duża (do 500px)'), ('FULL', 'Pełna szerokość'), ('CUSTOM', 'Niestandardowy (własna szerokość)')], default='FULL', help_text='Wybierz rozmiar wyświetlanej miniatury na liście postów.', max_length=6, verbose_name='Rozmiar miniatury'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Treść posta'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Zaznacz, aby przypiąć post na górze listy. Posty nieprzypięte będą sortowane według daty publikacji.', verbose_name='Przypięty?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Zaznacz, jeśli post ma być widoczny publicznie.', verbose_name='Opublikowany?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pin_order',
            field=models.PositiveIntegerField(default=0, help_text='Niższa liczba = wyższa pozycja na liście. Używane tylko dla przypiętych postów.', verbose_name='Kolejność przypięcia'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Tytuł posta'),
        ),
    ]
