# Generated by Django 5.2.3 on 2025-06-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł strony')),
                ('slug', models.SlugField(blank=True, help_text="Przyjazny adres URL, np. 'o-nas'. Zostaw puste, aby wygenerować automatycznie.", max_length=200, unique=True)),
                ('content', models.TextField(verbose_name='Treść strony')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Strona',
                'verbose_name_plural': 'Strony',
                'ordering': ['title'],
            },
        ),
    ]
