# Generated by Django 5.2.3 on 2025-06-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_headers/', verbose_name='Obraz nagłówkowy'),
        ),
    ]
