# Generated by Django 5.2.3 on 2025-06-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Zaznacz, jeśli strona ma być widoczna publicznie.', verbose_name='Opublikowana'),
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0, help_text='Kolejność wyświetlania w menu. Niższa liczba oznacza wyższą pozycję.', verbose_name='Kolejność'),
        ),
    ]
