# Generated by Django 5.2.3 on 2025-06-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_is_published_page_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Strona', 'verbose_name_plural': 'Strony'},
        ),
    ]
