# Generated by Django 5.2.3 on 2025-06-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_page_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='pages_thumbnails/', verbose_name='Obraz miniatury'),
        ),
        migrations.AddField(
            model_name='page',
            name='thumbnail_alignment',
            field=models.CharField(choices=[('LEFT', 'Do lewej'), ('RIGHT', 'Do prawej'), ('CENTER', 'Na środku')], default='CENTER', max_length=6, verbose_name='Wyrównanie miniatury'),
        ),
        migrations.AddField(
            model_name='page',
            name='thumbnail_custom_width',
            field=models.PositiveIntegerField(blank=True, help_text="Wpisz szerokość w pikselach, jeśli powyżej wybrano 'Niestandardowy'.", null=True, verbose_name='Niestandardowa szerokość (px)'),
        ),
        migrations.AddField(
            model_name='page',
            name='thumbnail_size',
            field=models.CharField(choices=[('S', 'Mała (do 200px)'), ('M', 'Średnia (do 350px)'), ('L', 'Duża (do 500px)'), ('FULL', 'Pełna szerokość'), ('CUSTOM', 'Niestandardowy (własna szerokość)')], default='FULL', max_length=6, verbose_name='Rozmiar miniatury'),
        ),
    ]
